# Generated by Django 2.2.16 on 2021-01-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('prediction_1', models.CharField(max_length=100)),
                ('prediction_2', models.CharField(max_length=100)),
                ('prediction_3', models.CharField(max_length=100)),
                ('recommendation_1', models.CharField(max_length=100)),
                ('recommendation_2', models.CharField(max_length=100)),
                ('recommendation_3', models.CharField(max_length=100)),
            ],
        ),
    ]
