# Generated by Django 2.2.16 on 2021-01-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('start_case_number', models.IntegerField()),
                ('end_case_number', models.IntegerField()),
                ('prediction_output_file', models.FileField(upload_to='data_pool')),
                ('code_value_map', models.FileField(upload_to='data_pool')),
                ('test_sheet_file', models.FileField(upload_to='data_pool')),
                ('master_log', models.FileField(upload_to='data_pool')),
                ('recommendation_sheet_file', models.FileField(upload_to='data_pool')),
            ],
        ),
    ]
