# Generated by Django 2.2.16 on 2021-01-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_user',
            old_name='code_value_map',
            new_name='data_input_file',
        ),
        migrations.RemoveField(
            model_name='ad_user',
            name='master_log',
        ),
        migrations.RemoveField(
            model_name='ad_user',
            name='recommendation_sheet_file',
        ),
        migrations.RemoveField(
            model_name='ad_user',
            name='test_sheet_file',
        ),
    ]
