# Generated by Django 2.2.16 on 2021-01-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210125_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_user',
            name='recommendation_file',
            field=models.FileField(default=0, upload_to='data_pool'),
            preserve_default=False,
        ),
    ]
