# Generated by Django 2.2.16 on 2021-01-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ad_user_recommendation_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('prediction_1_dropdown', models.FileField(upload_to='data_pool')),
                ('prediction_2_dropdown', models.FileField(upload_to='data_pool')),
                ('prediction_3_dropdown', models.FileField(upload_to='data_pool')),
                ('recommendation_1_dropdown', models.FileField(upload_to='data_pool')),
                ('recommendation_2_dropdown', models.FileField(upload_to='data_pool')),
                ('recommendation_3_dropdown', models.FileField(upload_to='data_pool')),
            ],
        ),
    ]
