# Generated by Django 2.2.16 on 2021-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('edtech', models.CharField(max_length=100)),
            ],
        ),
    ]
